In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

1.10.0


In [2]:
X=np.load('T22Audio/feat_X.npy')
Y=np.load('T22Audio/feat_Y.npy')
Zeros=X==0
offset=X.min()
X=X-X.min()
X[Zeros]=0
X=X.reshape(X.shape[0],13,13)
dicY={'a':0,'b':1,'d':2,'e':3,'f':4,'g':5,'i':6,'k':7,'l':8,'m':9,'n':10,'n~':11,'o':12,'p':13,'r':14,'r(':15,'s':16,'t':17,'tS':18,'u':19,'x':20,'Z':21}
Y=[dicY[key] for key in Y]
Y=np.array(Y, dtype='uint8')
sizeInp=X.shape[0]
permutation = np.random.permutation(sizeInp)
X=X[permutation]
Y=Y[permutation]
train_X=X[:int(0.8*sizeInp)]
test_X=X[int(0.8*sizeInp):]
train_Y=Y[:int(0.8*sizeInp)]
test_Y=Y[int(0.8*sizeInp):]

In [3]:
train_X=train_X/X.max()
test_X=test_X/X.max()

In [4]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(13, 13)),
    keras.layers.Dense(220, activation=tf.nn.relu),
    keras.layers.Dense(440, activation=tf.nn.relu),
    keras.layers.Dense(22, activation=tf.nn.softmax)
])

In [5]:
sgd=keras.optimizers.SGD(lr=0.05, momentum=0.0, decay=0.0, nesterov=False)
model.compile(optimizer=sgd, 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [6]:
model.fit(train_X, train_Y, epochs=100, validation_data=(test_X, test_Y))

Train on 184913 samples, validate on 46229 samples
Epoch 1/100
184913/184913 [==============================] - 8s 43us/step - loss: 1.2898 - acc: 0.5777 - val_loss: 1.0592 - val_acc: 0.6469
Epoch 2/100
184913/184913 [==============================] - 7s 37us/step - loss: 1.0006 - acc: 0.6619 - val_loss: 0.9442 - val_acc: 0.6796
Epoch 3/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.9137 - acc: 0.6904 - val_loss: 0.9575 - val_acc: 0.6719
Epoch 4/100
184913/184913 [==============================] - 7s 37us/step - loss: 0.8613 - acc: 0.7073 - val_loss: 0.8531 - val_acc: 0.7105
Epoch 5/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.8242 - acc: 0.7203 - val_loss: 0.8282 - val_acc: 0.7168
Epoch 6/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.7970 - acc: 0.7296 - val_loss: 0.8996 - val_acc: 0.6918
Epoch 7/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.7742 - acc: 0.7362 - val_

Epoch 59/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4773 - acc: 0.8337 - val_loss: 0.6137 - val_acc: 0.7963
Epoch 60/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4757 - acc: 0.8350 - val_loss: 0.6019 - val_acc: 0.8003
Epoch 61/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4720 - acc: 0.8359 - val_loss: 0.5678 - val_acc: 0.8103
Epoch 62/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4700 - acc: 0.8358 - val_loss: 0.6333 - val_acc: 0.7857
Epoch 63/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4687 - acc: 0.8369 - val_loss: 0.5872 - val_acc: 0.8024
Epoch 64/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4655 - acc: 0.8379 - val_loss: 0.5986 - val_acc: 0.8001
Epoch 65/100
184913/184913 [==============================] - 7s 36us/step - loss: 0.4633 - acc: 0.8386 - val_loss: 0.5915 - val_acc: 0.8030
Epoch 66/100


In [7]:
all_weights = []
for layer in model.layers:
   w = layer.get_weights()
   all_weights.append(w)

In [8]:
model.layers[1].get_weights()[1]

array([ 8.4929049e-02,  5.3048217e-01, -4.5747450e-03,  6.0277241e-01,
        7.7750385e-02, -1.1600584e+00, -5.3903723e-01, -1.6906472e+00,
        3.3169991e-01, -9.6787417e-01, -4.2177236e-01,  2.1818824e-01,
        9.1007060e-01, -1.1213694e+00,  9.7857360e-03, -5.9380543e-01,
       -2.9633674e-04,  3.0850330e-01, -1.3269011e+00, -4.1660942e-02,
        0.0000000e+00,  0.0000000e+00,  7.0806789e-01,  8.6511475e-01,
       -2.5072264e-02,  3.6205772e-02, -1.7848340e-03,  4.0982097e-01,
       -6.5771639e-03, -2.5260197e-02, -2.1304950e-01, -3.7987834e-01,
       -8.8366824e-01, -8.8097423e-01,  1.0680401e+00,  1.5043755e+00,
       -3.5329816e-01, -3.0801874e-01,  7.8158705e-03,  0.0000000e+00,
        0.0000000e+00, -1.0878881e+00,  2.0817424e-01, -1.0134062e+00,
       -1.6028447e-02,  6.3150381e-03,  5.2016205e-01, -7.0770504e-03,
       -5.1567656e-01,  4.0037337e-01, -7.2874492e-01, -6.5662098e-01,
       -1.1072156e+00, -3.5748474e-02, -2.6720688e-01,  3.9069004e-02,
      

In [9]:
model.layers[2].get_weights()[1]

array([-1.29710168e-01, -3.31659734e-01, -4.17743623e-01, -2.18016788e-01,
       -9.11898136e-01, -1.52209446e-01, -6.60444498e-01, -6.44696414e-01,
       -8.23727190e-01, -1.71148986e-01,  4.10671234e-02, -3.05495948e-01,
        3.03565990e-02,  6.92630351e-01, -4.94317949e-01,  2.82953102e-02,
       -5.45569602e-03,  1.55914472e-02, -3.94847155e-01, -6.40891671e-01,
        2.48488244e-02, -6.32955670e-01,  1.68954045e-01, -3.40410888e-01,
       -3.19063902e-01, -2.22032771e-01, -4.28591669e-01, -3.51604447e-03,
       -2.62921024e-02, -5.82091957e-02,  2.84674197e-01, -8.17230642e-02,
        4.78835136e-01, -5.33397794e-01, -4.25134510e-01,  4.14287299e-01,
        5.62653780e-01,  3.59982252e-01,  2.23973412e-02, -1.19621962e-01,
        8.46407004e-03,  4.22335446e-01, -8.66457727e-03, -2.57433616e-02,
       -2.68913388e-01, -4.33174282e-01, -4.14096206e-01, -5.36361001e-02,
       -1.83229834e-01, -9.43126902e-02, -9.56229508e-01, -4.45703745e-01,
       -3.54730695e-01,  

In [10]:
model.layers[3].get_weights()[0]

array([[-0.42695224, -0.19081813,  0.11621566, ..., -0.33536398,
        -0.05244092,  0.02520592],
       [ 0.30221143,  0.2226755 ,  0.4556592 , ...,  0.28280792,
        -0.0959378 , -0.35765564],
       [-0.09252478,  0.65858835,  0.21123666, ..., -0.384522  ,
         0.0810954 ,  0.58949894],
       ...,
       [ 0.0750394 , -0.19279373,  0.17000426, ..., -0.00679524,
         0.18455437,  0.36261737],
       [-0.1356139 ,  0.04931086,  0.47636428, ...,  0.02002008,
         0.31689736, -0.10657631],
       [ 0.34062478,  0.0347233 ,  0.08123791, ..., -0.8730093 ,
         0.34356192,  0.13432024]], dtype=float32)